services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: z_users
    ports:
      - "3306:3306"
    volumes:
    - ./mysql_data:/var/lib/mysql
    - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_node
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - mysqldb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_nginx
    restart: always
    ports:
      - "3004:80"
    depends_on:
      - backend